module.exports = {
  someSidebar: {
    '编程语言特性': [
      'lang/README',
      'lang/comment',
      'lang/data_type',
      'lang/oop',
    ],
    'Flutter开发': [
      'flutter/README',
      'flutter/layout',
      'flutter/ajax',
      'flutter/fish-redux',
      'flutter/project',
      'flutter/deployment',
      'flutter/mixin',
      'flutter/dev-plugin',
      'flutter/plugin',
      'flutter/issue',
    ],
    'Web前端': ['f2e/README', 'f2e/redux'],
    'IOS开发': ['ios/README', 'ios/oc'],
    'Android开发': [
      'android/README',
      'android/ui',
      'android/view',
      'android/activity',
      'android/net',
      'android/store',
      'android/sdk',
      'android/animate',
      'android/high-level',
      'android/animate',
    ],
    '基础知识': ['compute/README', 'compute/IEEE754'],
    '数据结构与算法': ['algo/README', 'algo/bitwise'],
  },
};
