declare type TypeName<T> = T extends string ? 'string' : T extends number ? 'number' : T extends boolean ? 'boolean' : T extends undefined ? 'undefined' : T extends Function ? 'function' : 'object';
declare type T1 = TypeName<string>;
declare type T2 = TypeName<string[]>;
declare type T3 = TypeName<string | string[]>;
declare type Diff<T, U> = T extends U ? never : T;
declare type T4 = Diff<'a' | 'b' | 'c', 'a' | 'e'>;
declare type NotNull<T> = Diff<T, undefined | null>;
declare type T5 = NotNull<string | number | undefined | null>;
declare let t5: T5;
declare type T6 = Extract<'a' | 'b' | 'c', 'a'>;
declare type T7 = ReturnType<() => string>;
